FROM rust:alpine as builder

WORKDIR /usr/src/atilink
RUN USER=root
RUN apk add pkgconfig openssl-dev libc-dev
COPY ./commons ./commons
COPY ./client ./client
RUN cargo build --release --manifest-path commons/Cargo.toml
RUN cargo build --release --manifest-path client/Cargo.toml

FROM alpine:latest
RUN apk update

COPY --from=builder /usr/src/atilink/client/target/release/client /usr/local/bin/
