[package]
name = "commons"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
bincode = "1.3.3"
flate2 = "1.0.35"
md5 = "0.7.0"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
sha256 = "1.5.0"
